version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./../../../app:/usr/wikia/slot1/current/src
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-wikia
  php-wikia:
    build: .
    volumes:
      - ./../../../app:/usr/wikia/slot1/current/src
      - ./../../../config:/usr/wikia/slot1/current/config
      - ./../../../cache/messages:/usr/wikia/slot1/current/cache/messages
