version: '2'

services:
  web:
    image: nginx:1.14.0
    ports:
      - "80:8080"
    volumes:
      - ../base/base.inc.template:/etc/nginx/conf.d/base.inc.template
      - ../base/lang-path.conf:/etc/nginx/conf.d/lang-path.conf
      - ../base/wikia.com.conf:/etc/nginx/conf.d/wikia.com.conf
      - ../base/rewrites.conf:/etc/nginx/conf.d/rewrites.conf
      - ../base/redirects.conf:/etc/nginx/conf.d/redirects.conf
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ../../../app/skins:/usr/wikia/slot1/current/src/skins
      - ../../../app/resources:/usr/wikia/slot1/current/src/resources
      - ../../../app/extensions:/usr/wikia/slot1/current/src/extensions
      - ../../../app/apple-touch-icon.png:/usr/wikia/slot1/current/src/apple-touch-icon.png
    environment:
      - FASTCGI_READ_TIMEOUT=180s
    depends_on:
      - php-wikia
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/base.inc.template > /etc/nginx/conf.d/base.inc '$$FASTCGI_READ_TIMEOUT' && exec nginx -g 'daemon off;'"
  php-wikia:
    image: php-wikia-dev
    volumes:
      - ../../../app:/usr/wikia/slot1/current/src
      - ../../../config:/usr/wikia/slot1/current/config
      - ../../../cache:/usr/wikia/slot1/current/cache/messages
    depends_on:
      - memcached
    environment:
      - MEMCACHED_SERVER=memcached:11211
      - WIKIA_DATACENTER=poz
      - WIKIA_ENVIRONMENT=dev
      - WIKIA_DEV_DOMAIN=dev.wikia-local.com
      - LOG_SOCKET_ONLY=yes
      - LOG_SOCKET_ADDRESS=tcp://logger:9999
  memcached:
    image: memcached:alpine
  # MW log output, see K8s_LOGGING.md
  logger:
    image: artifactory.wikia-inc.com/sus/mediawiki-logger:latest
