dist: trusty
sudo: false
language: php
php: 7.0
install:
  - pecl channel-update pecl.php.net
  - pecl install uopz
  - composer require mustache/mustache
  - rm LocalSettings.php
  - mysql -e 'create database its_a_mw;'
  - php maintenance/install.php --dbtype mysql --dbuser root --dbname its_a_mw --dbpath $(pwd) --pass nyan --server http://localhost TravisWiki admin
script:
  - cd tests && ./php-all
