apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-${SANDBOX_NAME}
  namespace: prod
  labels:
    app: mediawiki-${SANDBOX_NAME}
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  progressDeadlineSeconds: 180
  selector:
    matchLabels:
      app: mediawiki-${SANDBOX_NAME}
  template:
    metadata:
      labels:
        app: mediawiki-${SANDBOX_NAME}
    spec:
      containers:
        - name: nginx
          image: artifactory.wikia-inc.com/sus/mediawiki-sandbox-nginx:${IMAGE_TAG}
          livenessProbe:
            httpGet:
              path: /health/check
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/check
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
        - name: php
          image: artifactory.wikia-inc.com/sus/mediawiki-sandbox-php:${IMAGE_TAG}
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 9000
            timeoutSeconds: 5
          env:
            - name: WIKIA_DATACENTER
              value: "${SANDBOX_DATACENTER}"
            - name: WIKIA_ENVIRONMENT
              value: "${SANDBOX_ENVIRONMENT}"
            - name: HOSTNAME_OVERRIDE
              value: "${SANDBOX_NAME}"
            - name: LOG_SOCKET_ONLY
              value: "yes"
            - name: LOG_SOCKET_ADDRESS
              value: "tcp://localhost:9999"
          resources:
            limits:
              cpu: "4"
              memory: "1300Mi"
            requests:
              cpu: "400m"
              memory: "800Mi"
        # MW log output, see K8s_LOGGING.md
        - name: logger
          image: artifactory.wikia-inc.com/sus/mediawiki-logger:latest
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-${SANDBOX_NAME}
spec:
  selector:
    app: mediawiki-${SANDBOX_NAME}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mediawiki-${SANDBOX_NAME}-ingress
spec:
  rules:
    - host: "${SANDBOX_NAME}.wikia.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: mediawiki-${SANDBOX_NAME}
              servicePort: 80
