apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-prod
  namespace: prod
  labels:
    app: mediawiki-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mediawiki-prod
  template:
    metadata:
      labels:
        app: mediawiki-prod
    spec:
      containers:
        - name: nginx
          image: artifactory.wikia-inc.com/sus/mediawiki-prod-nginx:${IMAGE_TAG}
          ports:
            - containerPort: 8080
        - name: php
          image: artifactory.wikia-inc.com/sus/mediawiki-prod-php:${IMAGE_TAG}
          env:
            - name: WIKIA_DATACENTER
              value: "${DATACENTER}"
            - name: WIKIA_ENVIRONMENT
              value: "${ENVIRONMENT}"
            - name: LOG_SOCKET_ONLY
              value: "yes"
            - name: LOG_SOCKET_ADDRESS
              value: "tcp://localhost:9999"
          resources:
            limits:
              cpu: "4"
              memory: "1300Mi"
            requests:
              cpu: "400m"
              memory: "800Mi"
        # MW log output, see K8s_LOGGING.md
        - name: logger
          image: artifactory.wikia-inc.com/sus/mediawiki-logger:latest
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-prod
spec:
  selector:
    app: mediawiki-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mediawiki-prod-ingress
  annotations:
    traefik.frontend.priority: "1"
spec:
  rules:
    - host: "*.wikia.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: mediawiki-prod
              servicePort: 80
