---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "mediawiki-cronjob-${name}"
spec:
  schedule: ${schedule}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: logger
            image: artifactory.wikia-inc.com/sus/mediawiki-logger:latest
          - name: php
            image: artifactory.wikia-inc.com/sus/mediawiki-sandbox-php:${label}
            env:
             - name: SERVER_ID
               value: "${server_id}"
             - name: LOG_SOCKET_ONLY
               value: "yes"
             - name: LOG_SOCKET_ADDRESS
               value: "tcp://localhost:9999"
            args:
${args}
          restartPolicy: Never

