---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "mediawiki-cronjob-${name}"
spec:
  schedule: ${schedule}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: php
            image: artifactory.wikia-inc.com/sus/mediawiki-sandbox-php:0a5674e.c752111
            env:
             - name: LOG_STDOUT_ONLY
               value: "yes"
            args:
${args}
          restartPolicy: Never

